# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

CREATE TABLE "email"
(
  id bigint NOT NULL,
  cancelledstatus boolean,
  assunto text,
  conteudo text,
  errormsg text,
  datacadastro timestamp without time zone,
  dataenvio timestamp without time zone,
  situacao Long,
  usuariointerno_fk bigint,
  tramitavel_fk bigint,
  interessado_fk bigint,
  usuarioenvio_fk bigint,
  remetente Long,
  email character varying(255),
  evento text,
  codigorastreamento character varying(7),
  dataleiturarastreamento timestamp without time zone,
  dadosrastreamento character varying(500),
  usuarioexterno_fk bigint,
}

# --- !Downs

drop table "people" if exists;
drop table "email" if exists;
